# Generated by Django 4.0.2 on 2022-04-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Актуальность заказа'),
        ),
    ]
