# Generated by Django 4.0.2 on 2022-02-18 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discountCheck',
            field=models.BooleanField(default=False, verbose_name='Есть ли скидка?'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='products',
            name='recommendation',
            field=models.BooleanField(default=False, verbose_name='Рекомендуем?'),
        ),
    ]
