# Generated by Django 4.0.2 on 2022-03-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_discountcheck_alter_products_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(unique=True, verbose_name='Страница')),
                ('title', models.CharField(max_length=120, verbose_name='Блок title')),
                ('description', models.CharField(max_length=150, verbose_name='Блок description')),
                ('mein_text', models.TextField(verbose_name='Основной Сео текст страницы')),
            ],
        ),
    ]
