# Generated by Django 4.0.2 on 2022-03-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_ceo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ceo',
            new_name='Seo',
        ),
    ]
