# Generated by Django 4.0.2 on 2022-03-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_ceo_seo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'verbose_name': 'Seo', 'verbose_name_plural': 'Seo'},
        ),
        migrations.RenameField(
            model_name='seo',
            old_name='mein_text',
            new_name='main_text',
        ),
    ]
