# Generated by Django 4.0.2 on 2022-04-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_seo_options_rename_mein_text_seo_main_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='ФИО')),
                ('town', models.CharField(max_length=180, verbose_name='Город')),
                ('department', models.CharField(max_length=180, verbose_name='Отделение новой почты')),
                ('email', models.CharField(max_length=180, null=True, verbose_name='Email')),
                ('tel', models.CharField(max_length=180, verbose_name='Телефон')),
                ('comment', models.TextField(null=True, verbose_name='Коментарий')),
                ('order', models.TextField(verbose_name='Заказ')),
            ],
        ),
    ]
